### ISSUE TITLE
cryptsetup_keyfile_validation is not working properly

### ISSUE THREAD

**Issue by Lik-the-Fluffin** [desultory/ugrd#23]
ugrd 1.14.3
[My config](https://github.com/user-attachments/files/16324861/config.txt)
If /keys is not mounted [ValueError: [mounts] Failed to add fstab entry for: keys](https://github.com/user-attachments/files/16324895/error1.txt)

[Without that option](https://github.com/user-attachments/files/16324903/config.txt):
[FileNotFoundError: Key file not found: /keys/crypt_key.luks](https://github.com/user-attachments/files/16324905/error2.txt)

So currently it just replaces one error with another

**Comment by desultory** [comment]
Thanks for finding this, I'm in the middle of getting some tests added and will try to add this fix once I'm done with that.

I think the issue is here: https://github.com/desultory/ugrd/blob/main/src/ugrd/fs/mounts.py#L489

Even thought key validation is disabled for cryptsetup, it still tried to validate that mountpoint, i may add a "no_validate" option to mounts so this can be toggled off.

For the time being, I think you will have to disable validation entirely to get a successful build.

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/tree/fix(cryptsetup_key_validation)

That should fix it, you will need zenlib 2.2.0 for the latest version, it's not in the gentoo repos rn but I have already opened a pr

**Comment by desultory** [comment]
the changes should be live now, please let me know if there are still issues.

**Comment by Lik-the-Fluffin** [comment]
Emerged live ebuild "8d9ce9c"
config file unchanged

[still have the same error](https://github.com/user-attachments/files/16325930/error3.txt)

**Comment by desultory** [comment]
> Emerged live ebuild "8d9ce9c" config file unchanged
> 
> [still have the same error](https://github.com/user-attachments/files/16325930/error3.txt)

you've got to add "no_valdiate" to the mount config, that way it doesn't check for it and fail

**Comment by Lik-the-Fluffin** [comment]
sorry didn't read carefully enough, fixed the issue

**Comment by desultory** [comment]
> sorry didn't read carefully enough, fixed the issue

great, thanks for the feedback :)
